# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='bookId2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
