# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Snippets',
        ),
    ]
