# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_request_bookid2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='bookId2',
        ),
    ]
