# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_chatlist_partnername'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
