# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_request_bookid2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatList',
            fields=[
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chatLists', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('partner', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
