# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_chatlist_studentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedbook',
            name='sellerPrice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
