# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20161206_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedbook',
            name='sellerPrice',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
