# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20161206_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedbook',
            options={'ordering': ('created',)},
        ),
    ]
